# Generated by Django 4.1.4 on 2022-12-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Authors name")),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="Authors last name"),
                ),
                (
                    "email",
                    models.CharField(max_length=120, unique=True, verbose_name="Email"),
                ),
                ("phone", models.CharField(max_length=120, verbose_name="Phone")),
                (
                    "facebook_username",
                    models.CharField(max_length=120, verbose_name="Facebook username"),
                ),
            ],
            options={
                "db_table": "author",
            },
        ),
    ]
