# Generated by Django 4.1.4 on 2022-12-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(db_index=True, to="authors.author"),
        ),
    ]
