# Generated by Django 4.1.4 on 2023-01-03 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_author_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, to="books.genre"
            ),
        ),
    ]
